// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CardLinkController from "./card_link_controller"
application.register("card-link", CardLinkController)

import FileInputController from "./file_input_controller"
application.register("file-input", FileInputController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MultiSelectController from "./multi_select_controller"
application.register("multi-select", MultiSelectController)

import StickyHeaderController from "./sticky_header_controller"
application.register("sticky-header", StickyHeaderController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)
